apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.name }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi